"""add_custom_home_branding_settings

Revision ID: 03a8ea869158
Revises: fd7f4982f6fe
Create Date: 2026-06-14 16:47:59.853906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03a8ea869158'
down_revision = 'fd7f4982f6fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('user_home_layout', sa.String(length=50), server_default='both', nullable=False))
    op.add_column('tenants', sa.Column('header_title', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('header_subtitle', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('header_text_color', sa.String(length=7), server_default='#ffffff', nullable=False))
    op.add_column('tenants', sa.Column('header_text_bg', sa.String(length=50), server_default='none', nullable=False))
    op.add_column('tenants', sa.Column('header_text_pos_y', sa.String(length=50), server_default='center', nullable=False))
    op.add_column('tenants', sa.Column('header_text_pos_x', sa.String(length=50), server_default='center', nullable=False))
    op.add_column('tenants', sa.Column('header_text_animation', sa.String(length=50), server_default='none', nullable=False))
    op.add_column('tenants', sa.Column('vignettes', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'vignettes')
    op.drop_column('tenants', 'header_text_animation')
    op.drop_column('tenants', 'header_text_pos_x')
    op.drop_column('tenants', 'header_text_pos_y')
    op.drop_column('tenants', 'header_text_bg')
    op.drop_column('tenants', 'header_text_color')
    op.drop_column('tenants', 'header_subtitle')
    op.drop_column('tenants', 'header_title')
    op.drop_column('tenants', 'user_home_layout')
    # ### end Alembic commands ###
