"""add_logo_display_mode

Revision ID: 08208f89ded9
Revises: 51cd30b7f076
Create Date: 2026-06-14 15:31:19.508197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08208f89ded9'
down_revision = '51cd30b7f076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_display_mode', sa.String(length=50), server_default='logo_name', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_display_mode')
    # ### end Alembic commands ###
