"""sync_all_models

Revision ID: 0a2d9f852a92
Revises: 723e2bdbd2dd
Create Date: 2026-04-11 10:17:25.644750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2d9f852a92'
down_revision = '723e2bdbd2dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('waitlist_count', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('allow_waitlist', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('waitlist_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('tenants', 'welcome_message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'welcome_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('sessions', 'waitlist_count')
    op.drop_column('events', 'allow_waitlist')
    op.drop_column('events', 'waitlist_count')
    # ### end Alembic commands ###
