"""add_created_by_admin_to_user

Revision ID: 11c317014f46
Revises: ea5fc4a05bfb
Create Date: 2026-04-12 08:34:40.283866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c317014f46'
down_revision = 'ea5fc4a05bfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by_admin')
    # ### end Alembic commands ###
