"""add_event_groups

Revision ID: 184f3c64ff83
Revises: 4fed59314be0
Create Date: 2026-06-21 14:33:44.722514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184f3c64ff83'
down_revision = '4fed59314be0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'event_groups', ['event_group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'event_group_id')
    # ### end Alembic commands ###
