"""add_user_segments_fields

Revision ID: 19634822557c
Revises: 76c3afd05af9
Create Date: 2026-06-07 18:50:30.442519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19634822557c'
down_revision = '76c3afd05af9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('engagement_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('status_override', sa.String(length=50), nullable=True))
    
    # Populate existing rows
    op.execute("UPDATE offers SET engagement_type = 'ponctuel'")
    op.execute("UPDATE users SET is_archived = false")
    
    # Set nullable=False
    op.alter_column('offers', 'engagement_type', nullable=False)
    op.alter_column('users', 'is_archived', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status_override')
    op.drop_column('users', 'is_archived')
    op.drop_column('offers', 'engagement_type')
    # ### end Alembic commands ###
