"""add_advanced_tenant_settings

Revision ID: 21f5c8301e69
Revises: 
Create Date: 2026-03-23 09:11:13.591452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f5c8301e69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'subscription_type')
    op.drop_column('offers', 'is_popular')
    op.drop_column('offers', 'validity_end_date')
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'orderpaymentstatus') THEN CREATE TYPE orderpaymentstatus AS ENUM ('a_valider', 'paye', 'rembourse'); END IF; END $$;")
    op.execute("ALTER TABLE orders ALTER COLUMN payment_status DROP DEFAULT")
    op.execute("ALTER TABLE orders ALTER COLUMN payment_status TYPE orderpaymentstatus USING payment_status::orderpaymentstatus")
    op.execute("ALTER TABLE orders ALTER COLUMN payment_status SET DEFAULT 'a_valider'::orderpaymentstatus")
    op.alter_column('orders', 'payment_status',
               existing_type=sa.Enum('a_valider', 'paye', 'rembourse', name='orderpaymentstatus'),
               type_=sa.Enum('a_valider', 'paye', 'rembourse', name='orderpaymentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'a_valider'::character varying"))
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('cgv_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('rules_url', sa.String(length=500), nullable=True))
    
    # Add nullable then update then set NOT NULL
    op.add_column('tenants', sa.Column('registration_limit_mins', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('cancellation_limit_mins', sa.Integer(), nullable=True))
    op.execute("UPDATE tenants SET registration_limit_mins = 0, cancellation_limit_mins = 45")
    op.alter_column('tenants', 'registration_limit_mins', nullable=False)
    op.alter_column('tenants', 'cancellation_limit_mins', nullable=False)
    
    op.add_column('tenants', sa.Column('confirmation_email_body', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('allow_pay_later', sa.Boolean(), nullable=True))
    op.execute("UPDATE tenants SET allow_pay_later = true")
    op.add_column('tenants', sa.Column('payment_redirect_link', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('pay_now_instructions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('docs_accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'docs_accepted_at')
    op.drop_column('tenants', 'pay_now_instructions')
    op.drop_column('tenants', 'payment_redirect_link')
    op.drop_column('tenants', 'allow_pay_later')
    op.drop_column('tenants', 'confirmation_email_body')
    op.drop_column('tenants', 'cancellation_limit_mins')
    op.drop_column('tenants', 'registration_limit_mins')
    op.drop_column('tenants', 'rules_url')
    op.drop_column('tenants', 'cgv_url')
    op.drop_column('tenants', 'logo_url')
    op.alter_column('orders', 'payment_status',
               existing_type=sa.Enum('a_valider', 'paye', 'rembourse', name='orderpaymentstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'a_valider'::character varying"))
    op.add_column('offers', sa.Column('validity_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('is_popular', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('subscription_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
