"""Add installment_id to finance

Revision ID: 22c997a192c3
Revises: 27a9fe234d6c
Create Date: 2026-05-15 10:53:13.860803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c997a192c3'
down_revision = '27a9fe234d6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_transactions', sa.Column('installment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'finance_transactions', 'installments', ['installment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.drop_column('finance_transactions', 'installment_id')
    # ### end Alembic commands ###
