"""add_finance_transactions_unique_constraints

Revision ID: 246c19d4959a
Revises: 5d2757d1e1a5
Create Date: 2026-07-07 16:17:17.722589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246c19d4959a'
down_revision = '5d2757d1e1a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_finance_transactions_installment_id', 'finance_transactions', ['installment_id'])
    op.create_unique_constraint('uq_finance_transactions_order_id', 'finance_transactions', ['order_id'])
    op.create_unique_constraint('uq_finance_transactions_registration_id', 'finance_transactions', ['registration_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_finance_transactions_registration_id', 'finance_transactions', type_='unique')
    op.drop_constraint('uq_finance_transactions_order_id', 'finance_transactions', type_='unique')
    op.drop_constraint('uq_finance_transactions_installment_id', 'finance_transactions', type_='unique')
    # ### end Alembic commands ###
