"""Add finance accounts

Revision ID: 27a9fe234d6c
Revises: 3f23321a81a7
Create Date: 2026-05-15 10:40:39.425953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a9fe234d6c'
down_revision = '3f23321a81a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_transactions', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'finance_transactions', 'finance_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.drop_column('finance_transactions', 'account_id')
    # ### end Alembic commands ###
