"""add_activity_credits_to_offer_and_order

Revision ID: 28d257ead9c0
Revises: f7011a0ce59b
Create Date: 2026-07-15 20:20:48.598136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d257ead9c0'
down_revision = 'f7011a0ce59b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('activity_credits', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('activity_credits', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_activity_credits', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'offer_snap_activity_credits')
    op.drop_column('orders', 'activity_credits')
    op.drop_column('offers', 'activity_credits')
    # ### end Alembic commands ###
