"""Add limit fields to Order with default

Revision ID: 2a7b1ced1155
Revises: 6059b9ceff1b
Create Date: 2026-07-14 14:49:29.773157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7b1ced1155'
down_revision = '6059b9ceff1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('limit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('limit_period', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('limit_rollover', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('accumulated_rollover', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'accumulated_rollover')
    op.drop_column('orders', 'limit_rollover')
    op.drop_column('orders', 'limit_period')
    op.drop_column('orders', 'limit_amount')
    # ### end Alembic commands ###
