"""split_pay_later_settings

Revision ID: 36a3b4815900
Revises: 4b3d354f34d1
Create Date: 2026-05-08 15:31:57.919660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a3b4815900'
down_revision = '4b3d354f34d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('allow_pay_later_offers', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('allow_pay_later_events', sa.Boolean(), nullable=True))
    
    # Migrate data
    op.execute("UPDATE tenants SET allow_pay_later_offers = allow_pay_later, allow_pay_later_events = allow_pay_later")
    
    op.drop_column('tenants', 'allow_pay_later')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('allow_pay_later', sa.BOOLEAN(), autoincrement=False, nullable=True))
    
    # Migrate data back (take from offers by default)
    op.execute("UPDATE tenants SET allow_pay_later = allow_pay_later_offers")
    
    op.drop_column('tenants', 'allow_pay_later_events')
    op.drop_column('tenants', 'allow_pay_later_offers')
    # ### end Alembic commands ###
