"""add_invoice_fields_to_orders

Revision ID: 37f04bf619ec
Revises: bc0565b21ddb
Create Date: 2026-03-30 13:13:16.804303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f04bf619ec'
down_revision = 'bc0565b21ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_credit_transactions_offer', 'credit_transactions', ['offer_id'], unique=False)
    op.alter_column('offers', 'price_lump_sum_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('offers', 'is_unlimited',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Indique si l'offre inclut un nombre illimité de cours",
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    # Added manually because autogenerate missed them (already added to DB)
    op.add_column('orders', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('invoice_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'is_unlimited',
               existing_type=sa.BOOLEAN(),
               comment="Indique si l'offre inclut un nombre illimité de cours",
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('offers', 'price_lump_sum_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_credit_transactions_offer', table_name='credit_transactions')
    # ### end Alembic commands ###
