"""Add created_by_admin to User

Revision ID: 396aaeb0f6e2
Revises: 11c317014f46
Create Date: 2026-04-12 08:45:55.461146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396aaeb0f6e2'
down_revision = '11c317014f46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
