"""add_survey_tables

Revision ID: 3e5267cc2ad3
Revises: 22c997a192c3
Create Date: 2026-05-17 16:58:49.208735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5267cc2ad3'
down_revision = '22c997a192c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('survey_type', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_survey_campaign_event', 'survey_campaigns', ['event_id'], unique=False)
    op.create_index('idx_survey_campaign_tenant', 'survey_campaigns', ['tenant_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['survey_campaigns.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_survey_response_campaign', 'survey_responses', ['campaign_id'], unique=False)
    op.create_index('idx_survey_response_tenant', 'survey_responses', ['tenant_id'], unique=False)
    op.create_index('idx_survey_response_token', 'survey_responses', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_survey_response_token', table_name='survey_responses')
    op.drop_index('idx_survey_response_tenant', table_name='survey_responses')
    op.drop_index('idx_survey_response_campaign', table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index('idx_survey_campaign_tenant', table_name='survey_campaigns')
    op.drop_index('idx_survey_campaign_event', table_name='survey_campaigns')
    op.drop_table('survey_campaigns')
    # ### end Alembic commands ###
