"""add_tenant_payment_credentials

Revision ID: 3e5fb9fb61d4
Revises: 8401cdcd1314
Create Date: 2026-07-08 15:48:22.158545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5fb9fb61d4'
down_revision = '8401cdcd1314'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_publishable_key', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('stripe_secret_key', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('helloasso_client_id', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('helloasso_client_secret', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('helloasso_organization_slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'helloasso_organization_slug')
    op.drop_column('tenants', 'helloasso_client_secret')
    op.drop_column('tenants', 'helloasso_client_id')
    op.drop_column('tenants', 'stripe_secret_key')
    op.drop_column('tenants', 'stripe_publishable_key')
    # ### end Alembic commands ###
