"""add_finance_module

Revision ID: 3f23321a81a7
Revises: 5caf479f6bcf
Create Date: 2026-05-14 16:08:56.405348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f23321a81a7'
down_revision = '5caf479f6bcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
