"""add_login_customization_fields

Revision ID: 4b3d354f34d1
Revises: 396aaeb0f6e2
Create Date: 2026-04-14 09:48:57.739556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3d354f34d1'
down_revision = '396aaeb0f6e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('login_primary_color', sa.String(length=7), nullable=True))
    op.add_column('tenants', sa.Column('login_background_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('login_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'login_description')
    op.drop_column('tenants', 'login_background_url')
    op.drop_column('tenants', 'login_primary_color')
    # ### end Alembic commands ###
