"""Add session recurrence_id and instructor_name

Revision ID: 4c8b8fcba78a
Revises: effe1d7c45b7
Create Date: 2026-04-06 14:49:31.806169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8b8fcba78a'
down_revision = 'effe1d7c45b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('recurrence_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sessions_recurrence_id'), 'sessions', ['recurrence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_recurrence_id'), table_name='sessions')
    op.drop_column('sessions', 'recurrence_id')
    # ### end Alembic commands ###
