"""add_activity_fields

Revision ID: 4fed59314be0
Revises: e1949e9c6767
Create Date: 2026-06-19 07:10:17.902294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fed59314be0'
down_revision = 'e1949e9c6767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('allowed_activities', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_allowed_activities', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('activity_types', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'activity_types')
    op.drop_column('orders', 'offer_snap_allowed_activities')
    op.drop_column('offers', 'allowed_activities')
    # ### end Alembic commands ###
