"""add_google_review_prompt_settings

Revision ID: 51cd30b7f076
Revises: 64bde48d4872
Create Date: 2026-06-13 13:27:04.061963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cd30b7f076'
down_revision = '64bde48d4872'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('enable_review_prompts', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenants', sa.Column('google_review_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('review_prompt_threshold', sa.Integer(), server_default='5', nullable=False))
    op.add_column('users', sa.Column('review_prompt_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'review_prompt_sent_at')
    op.drop_column('tenants', 'review_prompt_threshold')
    op.drop_column('tenants', 'google_review_url')
    op.drop_column('tenants', 'enable_review_prompts')
    # ### end Alembic commands ###
