"""add_reminder_sent_at

Revision ID: 5caf479f6bcf
Revises: a86cfcdfcc5f
Create Date: 2026-05-14 15:40:42.230923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caf479f6bcf'
down_revision = 'a86cfcdfcc5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    op.add_column('event_registrations', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_registrations', 'reminder_sent_at')
    op.drop_column('bookings', 'reminder_sent_at')
    # ### end Alembic commands ###
