"""Add missing user preferences columns

Revision ID: 5ec8cea794c4
Revises: 4c8b8fcba78a
Create Date: 2026-04-06 14:58:02.732970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec8cea794c4'
down_revision = '4c8b8fcba78a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
