"""Add periodic limits

Revision ID: 6059b9ceff1b
Revises: e0df011e0428
Create Date: 2026-07-14 14:08:45.190745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6059b9ceff1b'
down_revision = 'e0df011e0428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('sequence_number', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('limit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('offers', sa.Column('limit_period', sa.String(length=50), nullable=True))
    op.add_column('offers', sa.Column('limit_rollover', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_limit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_limit_period', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_limit_rollover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'offer_snap_limit_rollover')
    op.drop_column('orders', 'offer_snap_limit_period')
    op.drop_column('orders', 'offer_snap_limit_amount')
    op.drop_column('offers', 'limit_rollover')
    op.drop_column('offers', 'limit_period')
    op.drop_column('offers', 'limit_amount')
    op.drop_column('installments', 'sequence_number')
    # ### end Alembic commands ###
