"""add_tenant_email

Revision ID: 64bde48d4872
Revises: e79026d15bc0
Create Date: 2026-06-13 06:37:07.957158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bde48d4872'
down_revision = 'e79026d15bc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'email')
    # ### end Alembic commands ###
