"""add location fields

Revision ID: 723e2bdbd2dd
Revises: 5ec8cea794c4
Create Date: 2026-04-07 21:46:58.469255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '723e2bdbd2dd'
down_revision = '5ec8cea794c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('locations', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'locations')
    op.drop_column('sessions', 'location')
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
