"""add_slogan_to_tenants

Revision ID: 76c3afd05af9
Revises: 3e9dcfa6a789
Create Date: 2026-06-04 21:18:19.727178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c3afd05af9'
down_revision = '3e9dcfa6a789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_campaigns', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('tenants', sa.Column('slogan', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'slogan')
    op.alter_column('survey_campaigns', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
