"""add_deleted_at_to_session_and_event

Revision ID: 7d33b4d3bad6
Revises: 8b1e1470e394
Create Date: 2026-07-05 19:17:30.413384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d33b4d3bad6'
down_revision = '8b1e1470e394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'deleted_at')
    op.drop_column('events', 'deleted_at')
    # ### end Alembic commands ###
