"""add_grace_period_settings_to_tenant

Revision ID: 7f62e949a52f
Revises: 19634822557c
Create Date: 2026-06-08 10:52:11.686831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f62e949a52f'
down_revision = '19634822557c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('grace_period_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tenants', sa.Column('grace_period_mode', sa.String(length=50), nullable=False, server_default='days'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'grace_period_mode')
    op.drop_column('tenants', 'grace_period_days')
    # ### end Alembic commands ###
