"""add_tenant_invitation_fields

Revision ID: 8b1e1470e394
Revises: ca0596d765d8
Create Date: 2026-07-05 13:12:18.867747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1e1470e394'
down_revision = 'ca0596d765d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('client_first_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('client_last_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('client_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('client_phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('client_address', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('sysadmin_notes', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('invitation_token', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('invitation_expires_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tenants_invitation_token'), 'tenants', ['invitation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_invitation_token'), table_name='tenants')
    op.drop_column('tenants', 'claimed_at')
    op.drop_column('tenants', 'invitation_expires_at')
    op.drop_column('tenants', 'invitation_token')
    op.drop_column('tenants', 'sysadmin_notes')
    op.drop_column('tenants', 'client_address')
    op.drop_column('tenants', 'client_phone')
    op.drop_column('tenants', 'client_email')
    op.drop_column('tenants', 'client_last_name')
    op.drop_column('tenants', 'client_first_name')
    # ### end Alembic commands ###
