"""make_installment_due_date_nullable

Revision ID: 936bc2bf171e
Revises: c374a4861887
Create Date: 2026-07-15 13:30:30.050987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936bc2bf171e'
down_revision = 'c374a4861887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installments', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installments', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
