"""add payment_link to events

Revision ID: a86cfcdfcc5f
Revises: 36a3b4815900
Create Date: 2026-05-14 15:30:59.684572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86cfcdfcc5f'
down_revision = '36a3b4815900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('payment_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'payment_link')
    # ### end Alembic commands ###
