"""add_helloasso_webhook_secret

Revision ID: b4d916d2740a
Revises: 3e5fb9fb61d4
Create Date: 2026-07-08 15:49:17.802289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d916d2740a'
down_revision = '3e5fb9fb61d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('helloasso_webhook_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'helloasso_webhook_secret')
    # ### end Alembic commands ###
