"""add_display_order_to_offers

Revision ID: bc0565b21ddb
Revises: fcccae690502
Create Date: 2026-03-24 09:01:31.059465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0565b21ddb'
down_revision = 'fcccae690502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('display_order', sa.Integer(), nullable=True))
    op.execute("UPDATE offers SET display_order = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'display_order')
    # ### end Alembic commands ###
