"""add_trigger_consumption_percent

Revision ID: c374a4861887
Revises: 2a7b1ced1155
Create Date: 2026-07-15 13:29:42.878079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c374a4861887'
down_revision = '2a7b1ced1155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('trigger_consumption_percent', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('trigger_consumption_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'trigger_consumption_percent')
    op.drop_column('offers', 'trigger_consumption_percent')
    # ### end Alembic commands ###
