"""add_event_group_id_to_finance_transactions

Revision ID: ca0596d765d8
Revises: 184f3c64ff83
Create Date: 2026-06-21 16:21:55.879679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0596d765d8'
down_revision = '184f3c64ff83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_transactions', sa.Column('event_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'finance_transactions', 'event_groups', ['event_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.drop_column('finance_transactions', 'event_group_id')
    # ### end Alembic commands ###
