"""add_order_snapshots

Revision ID: cfd5932e1ec7
Revises: 37f04bf619ec
Create Date: 2026-03-31 13:39:13.892047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd5932e1ec7'
down_revision = '37f04bf619ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'credits_used',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('credit_accounts', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('credit_accounts', 'total_purchased',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('credit_accounts', 'total_used',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('credit_transactions', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('credit_transactions', 'balance_after',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('offers', 'price_cents')
    op.add_column('orders', sa.Column('offer_snap_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_description', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_validity_days', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_validity_unit', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('offer_snap_is_validity_unlimited', sa.Boolean(), nullable=True))
    op.alter_column('orders', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('orders', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('orders', 'invoice_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('sessions', 'credits_required',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'credits_required',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('orders', 'invoice_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'invoice_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('orders', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('orders', 'offer_snap_is_validity_unlimited')
    op.drop_column('orders', 'offer_snap_validity_unit')
    op.drop_column('orders', 'offer_snap_validity_days')
    op.drop_column('orders', 'offer_snap_description')
    op.drop_column('orders', 'offer_snap_name')
    op.add_column('offers', sa.Column('price_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('credit_transactions', 'balance_after',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('credit_transactions', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('credit_accounts', 'total_used',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('credit_accounts', 'total_purchased',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('credit_accounts', 'balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bookings', 'credits_used',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
