"""remove_finance_transactions_order_id_unique

Revision ID: e0df011e0428
Revises: 22e264f7ecb4
Create Date: 2026-07-13 13:02:05.988205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0df011e0428'
down_revision = '22e264f7ecb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_finance_transactions_order_id', 'finance_transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_finance_transactions_order_id', 'finance_transactions', ['order_id'])
    # ### end Alembic commands ###
