"""add vignettes_title to tenant

Revision ID: e1949e9c6767
Revises: 03a8ea869158
Create Date: 2026-06-14 23:32:17.915162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1949e9c6767'
down_revision = '03a8ea869158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('vignettes_title', sa.String(length=255), server_default='À la une', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'vignettes_title')
    # ### end Alembic commands ###
