"""add_is_blocked_to_order

Revision ID: e5452ba0b10f
Revises: 7f62e949a52f
Create Date: 2026-06-08 16:15:15.054691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5452ba0b10f'
down_revision = '7f62e949a52f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_blocked')
    # ### end Alembic commands ###
