"""add_branding_visibility_flags

Revision ID: e79026d15bc0
Revises: e5452ba0b10f
Create Date: 2026-06-12 07:52:28.689555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79026d15bc0'
down_revision = 'e5452ba0b10f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('show_logo', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenants', sa.Column('show_name', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenants', sa.Column('show_slogan', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'show_slogan')
    op.drop_column('tenants', 'show_name')
    op.drop_column('tenants', 'show_logo')
    # ### end Alembic commands ###
