"""add_category_display_order_to_offers

Revision ID: effe1d7c45b7
Revises: cfd5932e1ec7
Create Date: 2026-04-05 21:32:59.742291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effe1d7c45b7'
down_revision = 'cfd5932e1ec7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('category_display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'category_display_order')
    # ### end Alembic commands ###
