"""multiple_thresholds_migration

Revision ID: f7011a0ce59b
Revises: 936bc2bf171e
Create Date: 2026-07-15 13:41:30.665637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7011a0ce59b'
down_revision = '936bc2bf171e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('trigger_consumption_percent', sa.Integer(), nullable=True))
    op.alter_column('offers', 'trigger_consumption_percent',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'trigger_consumption_percent',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'trigger_consumption_percent',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('offers', 'trigger_consumption_percent',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('installments', 'trigger_consumption_percent')
    # ### end Alembic commands ###
