"""add_offer_category

Revision ID: fcccae690502
Revises: 21f5c8301e69
Create Date: 2026-03-23 20:45:28.888209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcccae690502'
down_revision = '21f5c8301e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'category')
    # ### end Alembic commands ###
