"""replace_logo_display_mode_with_checkboxes

Revision ID: fd7f4982f6fe
Revises: 08208f89ded9
Create Date: 2026-06-14 15:38:58.846297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7f4982f6fe'
down_revision = '08208f89ded9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('user_header_show_logo', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenants', sa.Column('user_header_show_name', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('tenants', 'logo_display_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_display_mode', sa.VARCHAR(length=50), server_default=sa.text("'logo_name'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'user_header_show_name')
    op.drop_column('tenants', 'user_header_show_logo')
    # ### end Alembic commands ###
